[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd myrestu && python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["cd myrestu && python manage.py collectstatic --noinput"]

[start]

cmd = "cd myrestu && gunicorn myrestu.wsgi"