# Generated by Django 5.2.7 on 2025-11-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('feedback', models.CharField(max_length=200)),
                ('review', models.IntegerField(max_length=10)),
            ],
        ),
    ]
