# Generated by Django 5.2.7 on 2025-12-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakerestu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('request', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=10)),
                ('time', models.TimeField(max_length=10)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
