# Generated by Django 5.2.7 on 2025-12-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakerestu', '0002_bookingtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodDiliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.IntegerField(max_length=10)),
                ('items', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=200)),
                ('pin', models.IntegerField(max_length=10000)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
