# Generated by Django 5.2.7 on 2025-12-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakerestu', '0004_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNewAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='emailotp',
            name='is_verified',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
