# Generated by Django 5.2.7 on 2026-01-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakerestu', '0005_createnewaccount_emailotp_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repassword', models.CharField(max_length=200)),
            ],
        ),
    ]
