# Generated by Django 5.2.7 on 2026-01-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakerestu', '0006_repass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='fooddiliver',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
